# Generated by Django 4.1.7 on 2023-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0002_alter_file_user_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
