# Generated by Django 4.1.7 on 2023-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0003_file_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
