# Generated by Django 4.1.7 on 2023-06-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0004_file_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='FileApp.category'),
        ),
    ]
