# Generated by Django 4.1.7 on 2023-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0008_chat_file_chat_receive_user_chat_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default='chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(default='file_preview.png', upload_to='image/%Y/%m/%d'),
        ),
    ]
