# Generated by Django 4.1.7 on 2023-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_size',
            field=models.IntegerField(default=0),
        ),
    ]
