# Generated by Django 4.1.7 on 2023-06-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0003_subscription_size'),
        ('ProfileApp', '0004_profile_procent_size_alter_profile_total_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubscriptionApp.subscription'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='unregistered_user.png', upload_to='image/%Y/%m/%d'),
        ),
    ]
