# Generated by Django 4.1.7 on 2023-06-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0003_subscription_size'),
        ('ProfileApp', '0005_profile_subscription_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SubscriptionApp.subscription'),
        ),
    ]
